server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/userdb
    username: sahil
    password: sahil
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: user_service_schema
  application:
    name: user-service

jwt:
  secret: "123456789098765432345678765432345678987654567876543456789876545678987654"